# Generated by Django 3.0.5 on 2020-04-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email пользователя')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия пользователя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество пользователя')),
                ('birthdate', models.DateTimeField(verbose_name='Дата рождения')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user_type', models.CharField(default='user', max_length=50, verbose_name='Тип пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
