# Generated by Django 3.0.5 on 2020-04-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
