export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export const PROJECT_ERROR = 'PROJECT_ERROR';
export const USER_PROJECTS_LIST = 'USER_PROJECTS_LIST';
export const CLEAR_USER_PROJECTS = 'CLEAR_USER_PROJECTS';
export const CURRENT_PROJECT = 'CURRENT_PROJECT';
export const CLEAR_CURRENT_PROJECT = 'CLEAR_CURRENT_PROJECT';
export const PROJECTS_USERS_LIST = 'PROJECT_USERS';

export const TASK_ERROR = 'TASK_ERROR';
export const PROJECT_TASKS_LIST = 'PROJECT_TASKS_LIST';
export const CLEAR_PROJECT_TASKS = 'CLEAR_PROJECT_TASKS';
export const CURRENT_TASK = 'CURRENT_TASK';
export const CLEAR_CURRENT_TASK = 'CLEAR_CURRENT_TASK';

export const TODO_ERROR = 'TODO_ERROR';
export const TASK_TODOS_LIST = 'TASK_TODOS_LIST';
export const CLEAR_TASK_TODOS = 'CLEAR_TASK_TODOS';
export const CURRENT_TODO = 'CURRENT_TODO';
export const CLEAR_CURRENT_TODO = 'CLEAR_CURRENT_TODO';