export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export const PROJECT_ERROR = 'PROJECT_ERROR';
export const USER_PROJECTS_LIST = 'USER_PROJECTS_LIST';
export const CLEAR_USER_PROJECTS = 'CLEAR_USER_PROJECTS';