# Generated by Django 3.0.5 on 2020-04-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectUsersTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Тип пользователя')),
            ],
            options={
                'verbose_name': 'Тип пользователя',
                'verbose_name_plural': 'Типы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задания')),
                ('start_date', models.DateTimeField(verbose_name='Начало выполнения задания')),
                ('end_date', models.DateTimeField(verbose_name='Конец выполнения задания')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичное задание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='TODO')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Task')),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODOs',
            },
        ),
    ]
