# Generated by Django 3.0.5 on 2020-04-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200410_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(blank=True, default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(blank=True, default=False, verbose_name='Публичное задание'),
        ),
    ]
