# Generated by Django 3.0.5 on 2020-04-10 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200410_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Начало выполнения задания'),
        ),
    ]
