# Generated by Django 3.0.5 on 2020-05-14 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200410_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Тема проекта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 14, 15, 59, 55, 399220), verbose_name='Начало выполнения задания'),
        ),
    ]
