# Generated by Django 3.0.5 on 2020-04-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birthdate',
        ),
    ]
