# Generated by Django 3.0.5 on 2020-04-08 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0002_remove_account_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tasks',
            field=models.ManyToManyField(to='projects.Task'),
        ),
        migrations.CreateModel(
            name='PrjectUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectUsersTypes')),
            ],
            options={
                'verbose_name': 'Пользователь/Проект/Тип',
                'verbose_name_plural': 'Пользователи/Проекты/Типы',
            },
        ),
    ]
