# Generated by Django 3.0.5 on 2020-04-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0003_auto_20200408_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrjectUsers',
            new_name='ProjectUsers',
        ),
    ]
